name: nominal-roll-generator # you probably want to 'snapcraft register <name>'
version: '0.9.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Military personnel database & nominal roll generator # 79 char long summary
description: |
    This application archives military personnel records & generates nominal rolls in PDF format.
grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots
parts:
  nominal-roll-api:
    # See 'snapcraft plugins'
    source: .
    plugin: nodejs
    node-engine: 8.5.0
    build-packages:
      - python
      - build-essential
